export const Artikels = () => {
    return {
        datas: [{
            id: 1,
            judul: "Pengelasan",
            subjudul_1: "Pengertian Pengelasan", //!
            p_1: "Metode penyambungan logam telah ada sejak ribuan tahun lalu, yang banyak dilakukan oleh pandai besi yaitu menggunakan metode tempa. Kemudian pada abad ke 19 mulai dikenal pengelasan menggunakan gas oksigen dan gas acetylene yang menghasilkan nyala api yang panas. Bersamaan dengan itu juga dikenal pengelasan yang bersumber dari energi listrik.",
            subjudul_2:"Pengertian pengelasan", //!
            p_2: "Merujuk American Welding Society (AWS), pengertian pengelasan adalah suatu proses penyambungan dua material / lebih, biasanya berupa logam, dengan menggunakan energi panas sampai material yang akan disambung tersebut meleleh (melted) kemudian menyatu / berpadu (fused), dengan memberikan tekanan atau tidak, serta dengan memberikan bahan tambahan (consumable) atau tidak. ",
            judulpoin_1:"Ada 2 kata kunci yang menjadikan suatu proses disebut pengelasan, yaitu :",
            poin_1: "1-Material yang akan dilas bisa meleleh / mencair (melted)",
            poin_2: "2-Kemudian menyatu / berpadu menjadi solid kembali (fused).",
            p_3:"Teknik penyambungan logam dengan metode resistance, las gas dan las busur listrik adalah metode yang baik untuk penyambungan logam dan mulai dikembangkan sebelum perang dunia I.",
            gambar_1: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Thomsons-resistance-welding-transformer-768x322.png",
            subjudul_3:"METODE PENGELASAN:", //!
            subsubjudul_1:"RESISTANCE WELDING", //?
            p_4:"Resistance welding banyak digunakan untuk pengelasan pelat dengan tebal kurang dari 8 mm. Trafo untuk pengelasan resistance dapat menghasilkan 2000A pada 2V open circuit voltage. Pengelasan resistance dikembangkan menjadi beberapa jenis yaitu: Spot welding, Seam welding, Projection welding, Flash butt welding",
            p_5:"Pada perkembangan industri, spot welding adalah jenis pengelasan resistance yang banyak digunakan terutama pada industri otomotif. Prinsip kerja spot welding yaitu ada dua elektroda tembaga yang teraliri arus tinggi memberikan tekanan kepada pelat yang dalam posisi sambungan overlap, bersamaan proses tersebut pelat meleleh pada area spot elektroda. Metode spot welding dapat dilihat pada Gambar 2.",
            gambar_2: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Prinsip-kerja-spot-welding.png",
            subsubjudul_2: "GAS WELDING (LAS GAS)",
            p_6: "Gas yang sering digunakan untuk pengelasan adalah gas oksigen dan acetylene, pengelasan ini juga disebut oxy acetylene welding. Temperatur yang dihasilkan dari nyala api oxy acetylene welding sekitar 3100 °C, dan lebih tinggi dibandingkan jenis gas dari hidrokarbon yang lainnya.",
            p_7: "Pada aplikasi di industri, nyala api dari campuran oksigen dan acetylene selain digunakan untuk pengelasan juga banyak digunakan untuk proses pemotongan logam atau sering disebut oxy acetylene cutting. Peralatan untuk gas welding dapat dilihat pada Gambar 3.",
            gambar_3: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Peralatan-untuk-gas-welding.png",
            subsubjudul_3:"ARC WELDING (LAS BUSUR)",
            p_8:"Pada awalnya pengelasan busur menggunakan batang karbon kemudian menggunakan batang baja tanpa salutan. Pada perkembangannya karena proses pengelasan menggunakan batang baja sulit dilakukan dan banyak terjadi cacat pengelasan, maka dikembangkan elektroda dengan salutan atau yang biasa disebut flux/coating. Prinsip kerja las busur SMAW/ MMA ditunjukkan pada Gambar 4.",
            gambar_4:"https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Prinsip-kerja-las-SMAW-Shielded-Metal-Arc-Welding-atau-MMA-Manual-Metal-Arc.png",
            p_9: "Arc welding berkembang menjadi beberapa proses las yaitu: SAW (Submerged Arc Welding), GTAW (Gas Tungsten Arc Welding), GMAW (Gas Metal Arc Welding), FCAW (Flux Core Arc Welding)",
            gambar_5: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Pengelasan-SAW-Submerged-Arc-Welding.png",
            gambar_6: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Pengelasan-GTAW-Gas-Tungsten-Arc-Welding.png",
            p_10: "Pengelasan busur juga dikembangkan dari pengelasan secara manual, semi automatis dan otomatis (robot). Kebutuhan dalam penyambungan material menjadikan dasar dalam pemilihan jenis proses las yaitu proses las GTAW sangat baik digunakan untuk pengelasan pelat tipis, proses las SAW  cocok digunakan untuk pengelasan pelat tebal dan proses las GMAW dan FCAW sangan cocok digunakan untuk pengelasan yang membutuhkan penyambungan las yang panjang dan dapat diaplikasikan untuk semua posisi pengelasan.",
            gambar_7:"https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Pengelasan-GMAW-dan-FCAW-300x260.png",
            subjudul_4: "PROSES PENGELASAN YANG LAIN",
            subsubjudul_4: "PLASMA WELDING",
            p_11: "Plasma welding dikenal mulai tahun 1953, memiliki keunggulan yaitu konsentrasi panas lebih fokus dan menghasilkan temperature lebih tinggi, sehingga pengelasan jenis ini sangat cocok untuk pengelasan dengan kecepatan tinggi dengan heat input pada material lebih rendah dibandingkan tipe las busur lainnya.",
            gambar_8: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Plasma-welding-300x233.png",
            subsubjudul_5: "POWER-BEAM PROCCESES",
            p_12: "Pengelasan tipe Power beam procceses terdapat dua proses yaitu Elektrone Beam Welding dan Laser Welding. Proses pengelasan ini banyak digunakan pada industri penerbangan dan industri nuklir.",
            p_13: "Electrone Beam Welding memiliki karakter yaitu menghasilkan pengelasan dengan penetrasi yang dalam dan sempit memungkinkan dampak panas yang dialami oleh benda kerja atau material yang dilas dapat diminimalisir.",
            gambar_9: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/EBW-Electrone-Beam-Welding.png",
            p_14: "Laser Welding dalam pengaplikasiannya juga sering digunakan sebagai pemotongan yaitu laser cutting. Pada proses laser welding panas terkonsentrasi dan memungkinkan dilakukan pengelasan dengan kecepatan tinggi, untuk itu jenis pengelasan ini biasa diaplikasikan untuk penyambungan material tipis dan yang mudah terjadi deformasi.",
            gambar_10: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Laser-welding.png",
            subsubjudul_6: "FRICTION STIR WELDING",
            p_15: "Friction Stir Welding (FSW) banyak digunakan untuk penyambungan material aluminium pada industri penerbangan. Proses las FSW tidak menggunakan bahan tambah atau bahan pengisi, proses penyambungan material dengan cara memberikan gesekan menggunakan tool yang berputar pada area sambungan las. Putaran dan panas pada tool yang mengaduk bagian sambungan yang menjadikan kedua material menyatu.",
            gambar_11: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Friction-Stir-Welding-FSW.png",
            subjudul_5: "TERMINOLOGI PENGELASAN",
            p_16: "Tabel 1 adalah proses/ metode pengelasan dan kodifikasi pengelasan menurut ISO 4063.",
            gambar_12:"https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Referensi-nomor-proses-pengelasan-sesuai-ISO-4063.png",
            p_17: "Ringkasan dari proses pengelasan ditunjukkan pada gambar dibawah",
            gambar_13: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Ringkasan-Skema-proses-pengelasan.png",
            judulpoin_2: "Istilah dasar pada pengelasan dijelaskan dibawah ini:",
            poin_3: "> WELDMENT.Gabungan weld, Heat Afected Zone (HAZ) dan base metal.",
            poin_4: "> BUT WELD adalah menggabungkan dua material dari ujung ke ujung, pengelasan penuh (complete joint) dan tersambung kuat menjadi satu..",
            poin_5: "> FILLET WELD adalah menggabungkan 2 material pelat ke pelat atau pelat ke pipa tumpang tindih (over lapping) atau kedua bagian ditempatkan tegak lurus satu sama lain (misalkan membentuk T atau L)",
            poin_6: "> PRESSURE WELDING adalah pengelasan yang menggunakan gaya luar (tekanan dan gesekan) untuk menghasilkan sambungan dan tanpa bahan tambah atau bahan pengisi sehingga deformasi plastis pada sambungan yang dihasilkan lebih kecil.",
            poin_7: "> FUSION WELDING adalah penyambungan logam dengan memberikan energi panas pada logam dasar sampai mencair (melting) dan proses pengelasan dapat menggunakan bahan pengisi atau tanpa bahan pengisi.",
            poin_8: "> WELDING PROCEDURE SPESIFICATIONS (WPS) adalah dokumen prosedur pengelasan yang menjelaskan parameter dan variable yang digunakan sebagai petunjuk saat melakukan proses pengelasan untuk memastikan kualitas hasil lasan baik.",
            poin_9: "> DEPOSITE RATE adalah jumlah logam yang dipasok ke sambungan las persatuan waktu selama pengelasan.",
            poin_10: "> PARENT METAL adalah logam dasar yang di sambung atau di lapisi (surfacing) menggunakan proses pengelasan.",
            poin_11: "> LONGITUDINAL DIRECTIONAL adalah arah sepanjang pengelasan atau sejajar dengan pengelasan.",
            poin_12: "> TRANSVERSE DIRECTIONAL adalah arah sepanjang lebar lasan atau tegak lurus dengan las.",
            poin_13: "> SURFACING adalah memberikan lapisan pada permukaan bidang yang dilas dengan tujuan anti korosi, anti abrasi atau tahan panas dibandingkan logam induk.",
            poin_14: "> HEAT IMPUT adalah panas yang masuk ke material karena proses pengelasan. Heat input pada pengelasan dapat dihitung menggunakan rumus sebagai berikut:",
            gambar_14: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/rumus-heat-input.png",
            poin_15: "> HEAT AFFECTED ZONE (HAZ) adalah area diluar pengelasan yang tidak ikut mencair akan tetapi terdampak siklus panas saat proses pengelasan sehingga sifat fisik pada area tersebut berubah.",
            gambar_15: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Heat-Affected-Zone-HAZ.png",
            poin_16: "> TROATH THICKNESS adalah ukuran pengelasan fillet dihitung dengan mengacu pada ukuran Throat. Ukuran yang disyaratkan ditentukan pada gambar dalam hal ketebalan Throat (t) atau panjang Leg Length (l)",
            gambar_16: "https://i0.wp.com/allpro.co.id/wp-content/uploads/2021/03/Throat-Thickness-t-and-Leg-Length-l.png",
        },
        {
            id: 2,
            judul: "Jenis-jenis Mesin Perkakas Konvensional",
            p_1: "Pada artikel kali ini akan dibahas tentang jenis-jenis mesin perkakas konvensional. ",
            p_2: "Buat yang sudah terbiasa dengan mesin produksi atau memiliki latar belakang pendidikan teknik, tentunya sering mendengar kata mesin perkakas ini.",
            p_3: "Mesin perkakas merupakan alat mekanis yang digunakan untuk membuat komponen dari logam ataupun material padat lainnya.",
            p_4: "Mesin konvensional adalah sebuah mesin perkakas yang memanfaatkan energi listrik. Kemudian ditransfer menjadi gerak, baik menjadi gerak berputar atau gerakan bolak balik. ",
            p_5: "Mesin perkakas konvensional ini gerakan sumbunya, gerakan pemakanan dan pengaturan putarannya masih dioperasikan secara manual oleh operator mesin.",
            p_6: "Fungsi utama dari mesin perkakas ini dapat digunakan untuk melakukan proses manufaktur. Melakukan Proses terhadap raw materia menjadi benda kerja berupa komponen mekanik.",
            p_7: "Jenis-jenis Perkakas Mesin Konvensional yang biasa digunakan di bengkel-bengkel produksi adalah:",
            poin_1:"> Mesin Bubut (Turning Machine)",
            poin_2:"> Mesin Frais (Milling Machine)",
            poin_3:"> Mesin Gerinda (Grinding Machine)",
            poin_4:"> Mesin Bor (Drilling Machine)",
            subjudul_1: "Perkakas Mesin Bubut",
            p_8:"Mesin bubut adalah sebuah mesin perkakas yang digunakan untuk melakukan proses pemotongan logam. proses pemotongan tersebut dengan cara proses putar. Biasanya benda kerja yang diproses adalah benda kerja berbentuk silinder. benda kerja bentuk silinder pejal maupun berlubang.",
            p_9:"Proses bubut menghasilkan bagian-bagian mesin berbentuk silindris. Bentuk dasarnya dapat didefinisikan sebagai proses pemesinan permukaan luar benda silindris atau bubut rata.",
            gambar_1:"https://cdn-dannk.nitrocdn.com/axCwrmPgOwatYmZNzJPxvKWzaSdqJadf/assets/static/optimized/rev-a7fb710/wp-content/uploads/2018/07/lH.jpg",
            subjudul_2:"Mesin Frais",
            p_10:"Mesin frais adalah termasuk mesin perkakas proses pemotongan logam dengan proses putar juga. Proses pemesinan frais (milling) adalah proses penyayatan benda kerja menggunakan alat potong dengan mata potong banyak yang berputar. Permukaan yang disayat bisa berbentuk datar, menyudut, atau melengkung.",
            gambar_2:"https://www.pengelasan.net/wp-content/uploads/2020/01/Bagian-Bagian-Mesin-Frais.jpg",
            subjudul_3:"Mesin Gerinda",
            p_11:"Prinsip kerja mesin gerinda adalah roda gerinda berputar, kemudian bersentuhan dengan benda kerja dan terjadilah pemotongan.",
            gambar_3:"https://3.bp.blogspot.com/-NnVWImBbtCg/WKcIaeLkrFI/AAAAAAAAAn8/By46UW-In607EsMeb1C7K6knQlbh2kTWACLcB/s1600/grind5.jpg",
            subjudul_4:"Mesin Bor",
            p_12:"Mesin bor adalah mesin untuk membuat lubang berbentuk silinder dalam bahan yang pejal. Atau dapat digunakan untuk memperbesar Lubang bor.",
            gambar_4: "https://cf.shopee.co.id/file/5d9dff55bb9d87d256ca261a6bf5da67",


        }]
    }
}
